nodes:
<<<<<<< HEAD
  - address: 52.207.31.136
    internal_address: 172.31.93.144
=======
  - address: 44.202.217.18
    internal_address: 172.31.85.223
>>>>>>> feature/msp-22
    user: ubuntu
    role:
      - controlplane
      - etcd
      - worker

# ignore_docker_version: true

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ssh_key_path: ~/.ssh/call-rancher.pem

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"